name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable, beta ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build Components
        uses: actions-rs/cargo@v1
        with:
          command: build
        if: runner.os != 'Linux'
      - name: Build Components
        uses: actions-rs/cargo@v1
        with:
          command: build
        env:
          OPENSSL_STATIC: 1
          OPENSSL_LIB_DIR: /usr/lib64
          OPENSSL_INCLUDE_DIR: /usr/include/openssl
        if: runner.os == 'Linux'
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
